services:
  mysql_microservice:
    build: ./mysql-microservice
    container_name: mysql_microservice_container
    environment:
      MYSQL_ROOT_PASSWORD: 123412
      MYSQL_DATABASE: crud_task
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123412
    ports:
      - "3307:3306"
    volumes:
      - mysql_microservice_data:/var/lib/mysql
    networks:
      - my_network

  crud_task_db:
    image: mysql:8.0
    container_name: crud_task_db
    environment:
      MYSQL_ROOT_PASSWORD: 123412
      MYSQL_DATABASE: crud_task
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123412
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s

  backend:
    build: ./server-backend
    container_name: backend_container
    depends_on:  
      crud_task_db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_HOST: crud_task_db
      DB_USER: root
      DB_PASSWORD: 123412
      DB_NAME: crud_task
    networks:
      - my_network

  frontend:
    build: ./client-frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:  # Igual que en backend
      crud_task_db:
        condition: service_healthy

volumes:
  mysql_data:
  mysql_microservice_data:

networks:
  my_network: